"""empty message

Revision ID: 332b048d1134
Revises: 52e52d8bf773
Create Date: 2024-02-01 19:46:47.105191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332b048d1134'
down_revision = '52e52d8bf773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('holdings', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('watchlist', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('watchlist')
        batch_op.drop_column('holdings')

    # ### end Alembic commands ###
