"""empty message

Revision ID: 4d774d812bb5
Revises: 7a8a2a993785
Create Date: 2024-01-31 22:36:30.300234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d774d812bb5'
down_revision = '7a8a2a993785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watchlist', sa.Text(), server_default='[]', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('watchlist')

    # ### end Alembic commands ###
